# -*- coding: utf-8 -*-
"""module 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1APfAIISuA27ITPKEi1QtidTc3S56f5_C
"""

# SIRS score function 

def sirs_score(temp, hr, rr, wbc):
  dict = {}
  sirs = 0
  if(temp>38):
    sirs=sirs+1
    dict['temp'] = 'high'
  elif(temp<36):
    dict['temp'] = 'low'
    sirs=sirs+1
  else:
    dict['temp'] = 'normal'
  
  if(hr>90):
    dict['hr'] = 'high'
    sirs=sirs+1
  else:
    dict['hr'] = 'normal'

  if(rr>20):
    dict['rr'] = 'high'
    sirs=sirs+1
  else:
    dict['rr'] = 'normal'

  if(wbc>12):
    sirs=sirs+1
    dict['wbc'] = 'high'
  elif(wbc<4):
    dict['wbc'] = 'low'
    sirs=sirs+1
  else:
    dict['wbc'] = 'normal'

  return sirs,dict

##sample input
sirs_score(36.11,108,29,5.7)

