# -*- coding: utf-8 -*-
"""module3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atRFuOoVaGKCGznKtHFU-MvonjmVxe1n
"""

# Module 3 - medical recomendation

def medical_rec(sympt):
    rec={}
    hr_high=["Diuretics", "Beta-blockers", "ACE inhibitors", "Vasodilators", "Angiotensin II receptor blockers"]
    temp_high=["Acetaminophen", "Ibuprofen", "Aspirin"]
    wbc_high=["Antibiotics", "Anticonvulsants", "Antithyroid drugs","Arsenicals","Captopril","Chlorpromazine","Clozapine"]
    wbc_low=["Beta-adrenergic agonist","Corticosteroids","Epinephrine","Granulocyte colony-stimulating factor","Heparin","Lithium"]
    rr_high=["alprazolam", "clonazepam", "buspirone"]

    if(sympt['temp']=='high'):
        rec['high_temp']=temp_high
    
    if(sympt['rr']=='high'):
        rec['high_rr']=rr_high;
    
    if(sympt['hr']=='high'):
        rec['high_hr']=hr_high
    
    if(sympt['wbc']=='low'):
        rec['low_wbc']= wbc_low;
    elif(sympt['wbc']=='high'):
      rec['high_wbc']= wbc_high

    return rec;

#sample input
medical_rec({'hr': 'high', 'rr': 'high', 'temp': 'normal', 'wbc': 'normal'})

